name: Docker Deployment

on:
  push:
    paths:
      - 2_docker_deployment/**
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy App
        run: |
          echo "Running 2_docker_deployment.yaml"
          # Your deployment commands for App
