name: Docker Deployment

on:
  push:
    paths:
      - 2_docker_deployment/backend/**
      - 2_docker_deployment/frontend/**
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: 2_docker_deployment/backend
          file: 2_docker_deployment/backend/docker/Dockerfile
          push: true
          tags: gsarapura/craftech-2-docker-deployment-backend:latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: 2_docker_deployment/frontend
          file: 2_docker_deployment/frontend/docker/Dockerfile
          push: true
          tags: gsarapura/craftech-2-docker-deployment-frontend:latest