name: Docker Deployment

on:
  push:
    paths:
      - 3_ci_cd/**
    branches: [ three-ci-cd ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy App
        run: |
          echo "Running 3_ci_cd.yaml"
          # Your deployment commands for App
